### ISSUE TITLE
尝试添加一个自动领取邮件的功能

### ISSUE THREAD

**Issue by Whistick** [liqwang/Majsoul-Login#4]
您好，感谢提供的代码，非常impressive非常便利的实现方式！
就是我现在想着添加一个自动领取邮件的功能（虽然猫粮很抠，但我还是想着偶尔能白嫖一下），我能成功定位到layaCanvas并想着调用API去模拟点击，但是请问这个位置具体的数值是如何尝试出来的，请问有什么调试技巧吗？
期待回复~

**Comment by QuanQuan-CHO** [comment]
开发环境把这行注释掉(关闭headless模式)就可以看到对应浏览器窗口了，坐标可以在里面调试
https://github.com/QuanQuan-CHO/Majsoul-Login/blob/9169aadd95c7c8b0be497fe3c3130c1106f85799/login.py#L18

**Comment by Whistick** [comment]
谢谢我现在搞定了，已经试出来了，就是雀魂的领取邮件和删除邮件是同一个地方，第一天领取之后第二天重复这样的点击就会变成删除邮件了
`    # 5.check mails
    print('Check mails')
    ActionChains(driver)\
        .move_to_element_with_offset(screen, 350, -210)\
        .click()\
        .perform()
    sleep(5)
    ActionChains(driver)\
        .move_to_element_with_offset(screen, 400, -200)\
        .click()\
        .perform()
    ActionChains(driver)\
        .move_to_element_with_offset(screen,270, -230)\
        .click()\
        .perform()
    ActionChains(driver)\
        .move_to_element_with_offset(screen,50, -220)\
        .click()\
        .perform()
    ActionChains(driver)\
        .move_to_element_with_offset(screen,80, 190)\
        .click()\
        .perform()
    sleep(5)
    ActionChains(driver)\
        .move_to_element_with_offset(screen, 400, -200)\
        .click()\
        .perform()
    sleep(5)
    ActionChains(driver)\
        .move_to_element_with_offset(screen, 400, -200)\
        .click()\
        .perform()
    print('Complete!')
    sleep(5)`

**Comment by Whistick** [comment]
`
    # 5.check mails
    print('Check mails')
    ActionChains(driver)\
        .move_to_element_with_offset(screen, 350, -210)\
        .click()\
        .perform()
    sleep(5)
    ActionChains(driver)\
        .move_to_element_with_offset(screen, 400, -200)\
        .click()\
        .perform()
    ActionChains(driver)\
        .move_to_element_with_offset(screen,270, -230)\
        .click()\
        .perform()
    ActionChains(driver)\
        .move_to_element_with_offset(screen,50, -220)\
        .click()\
        .perform()
    ActionChains(driver)\
        .move_to_element_with_offset(screen,80, 190)\
        .click()\
        .perform()
    sleep(5)
    ActionChains(driver)\
        .move_to_element_with_offset(screen, 400, -200)\
        .click()\
        .perform()
    sleep(5)
    ActionChains(driver)\
        .move_to_element_with_offset(screen, 400, -200)\
        .click()\
        .perform()
    print('Complete!')
    sleep(5)
`
