### ISSUE TITLE
卡在第二步配置上

### ISSUE THREAD

**Issue by SNisuperC** [liqwang/majsoul-login#6]
依次配置EMAIL、PASSWD这步在Actions secrets / New secret下不知如何填写，请问大佬方便给个参考图示吗？

**Comment by liqwang** [comment]
<img width="361" alt="image" src="https://github.com/user-attachments/assets/36264bac-f375-42cc-b65b-2be85790e507">

**Comment by SNisuperC** [comment]
![image](https://github.com/user-attachments/assets/1d351a8d-3aa5-4f94-9df1-0b87beb873de)
请问是这样吗？

**Comment by liqwang** [comment]
![secret](https://github.com/user-attachments/assets/b99c9d9b-5d34-464e-bae5-7571de0c119f)

**Comment by SNisuperC** [comment]
运行成功啦，感谢大佬~
